Update install.yaml to use correct FQDN
upbound/universal-crossplane pull request #263
Opened 2022-07-21 21:45 UTC by jastang

### Description of your changes
In the [getting-started install instructions](https://cloud.upbound.io/docs/getting-started/build-control-plane/#install-via-cli), the sample `install.yaml` was still referencing `registry.upbound.io`, which needs to be updated before we build and push a new version of the xpkg from #243. 

I have:

- [ ] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

`kubectl get pkg` after applying the updated manifest shows:

```
➜  universal-crossplane git:(fix-getting-started-install) ✗ k get pkg
NAME                                               INSTALLED   HEALTHY   PACKAGE                                           AGE
configuration.pkg.crossplane.io/getting-started    True        True      xpkg.upbound.io/upbound/getting-started:latest    29s
```

2022-07-21 21:45 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/universal-crossplane?pullRequest=263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/universal-crossplane?pullRequest=263) before we can accept your contribution.<br/><hr/>**Jason Tang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/universal-crossplane?pullRequest=263) it.</sub>

2022-07-22 01:26 UTC, jbw976 requested changes
Sweet, thanks for catching this! The changes look good, but the CLA sign-off is not happy yet because there are multiple authors on the commits in this PR.

@jastang is it possible to ammend/update your commits so it's 1 single commit of the change that is authored and committed by the same account that has signed the CLA? I'd like to be complete with that.  Thank you! :)

2022-07-22 13:51 UTC, jastang commented
xref #238

2022-07-22 14:47 UTC, jbw976 approved these changes
sweet! the CLA bot is happy now with the single author, thanks for cleaning that up @jastang!

2022-07-22 14:47 UTC, merged